-- Contract Pipeline Summary Table
CREATE TABLE IF NOT EXISTS contract_pipeline_summary (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ticker VARCHAR(10) UNIQUE NOT NULL,
  total_active_contracts INTEGER DEFAULT 0,
  total_backlog_value_sar DECIMAL(18,2) DEFAULT 0,
  largest_single_contract_sar DECIMAL(18,2),
  largest_contract_title_en TEXT,
  largest_awarding_entity_en TEXT,
  annual_revenue_sar DECIMAL(18,2),
  backlog_to_revenue_ratio DECIMAL(8,2),
  revenue_visibility_months INTEGER,
  contracts_won_last_12m INTEGER DEFAULT 0,
  contracts_won_last_12m_value DECIMAL(18,2) DEFAULT 0,
  contracts_won_last_3m INTEGER DEFAULT 0,
  contracts_won_last_3m_value DECIMAL(18,2) DEFAULT 0,
  government_contract_percent DECIMAL(8,2),
  giga_project_contract_percent DECIMAL(8,2),
  top_client_concentration DECIMAL(8,2),
  pipeline_score INTEGER,
  pipeline_trend VARCHAR(20),
  has_neom_contract BOOLEAN DEFAULT FALSE,
  has_red_sea_contract BOOLEAN DEFAULT FALSE,
  has_qiddiya_contract BOOLEAN DEFAULT FALSE,
  has_diriyah_contract BOOLEAN DEFAULT FALSE,
  has_roshn_contract BOOLEAN DEFAULT FALSE,
  total_giga_exposure_sar DECIMAL(18,2) DEFAULT 0,
  last_contract_date DATE,
  last_updated TIMESTAMP DEFAULT NOW()
);
